name: IdanPlus Check

on:
  schedule:
    - cron: "0 6,18 * * *"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check latest version
        run: |
          DATA=$(curl -s https://api.github.com/repos/Fishenzon/repo/contents/zips/plugin.video.idanplus)

          FILE=$(echo "$DATA" | jq -r '.[].name' | grep plugin.video.idanplus- | sort -V | tail -n 1)
          NEW=$(echo $FILE | sed -E 's/.*-([0-9\.]+)\.zip/\1/')

          if [ -f backend/plugin_video_idanplus/addon.xml ]; then
            INSTALLED=$(grep -oP '<addon[^>]*version="\K[0-9\.]+' backend/plugin_video_idanplus/addon.xml | head -n1)
          else
            INSTALLED="none"
          fi

          echo "Installed version: $INSTALLED"
          echo "Latest version: $NEW"

          if [ "$INSTALLED" != "$NEW" ]; then
            echo "✅ New version available!"
          else
            echo "ℹ️ Already up to date"
          fi